---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-resource-sealos-io-v1-witelist
  failurePolicy: Fail
  name: mwitelist.kb.io
  rules:
  - apiGroups:
    - resource.sealos.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - witelists
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-resource-sealos-io-v1-witelist
  failurePolicy: Fail
  name: vwitelist.kb.io
  rules:
  - apiGroups:
    - resource.sealos.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - witelists
  sideEffects: None
